### ISSUE TITLE
Regex for postfix

### ISSUE THREAD

**Issue by ouafnico** [sous-chefs/fail2ban#29]
Hello

Using fail2ban on CentoS 7, tries for smtp relay are not blocked. 
Adding this regex solve the problem on postfix.conf. Can you add it by default ?

^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+[<HOST>]: 454 4.7.1 .*$

For info, log lines for these tries are :

Mar  1 18:26:24 server postfix/smtpd[14970]: NOQUEUE: reject: RCPT from unknown[50.60.146.24]: 454 4.7.1 returntest@mydnstools.info: Relay access denied; from=relaytest@mydnstools.info to=returntest@mydnstools.info proto=SMTP helo=<relaytest.mydnstools.info>
Mar  1 18:26:25 server postfix/smtpd[14970]: NOQUEUE: reject: RCPT from unknown[50.60.146.24]: 454 4.7.1 <returntest%mydnstools.info@mydomain.fr>: Relay access denied; from=relaytest@mydnstools.info to=<returntest%mydnstools.info@mydomain.fr> proto=SMTP helo=<relaytest.mydnstools.info>
Mar  1 18:26:25 server postfix/smtpd[14970]: NOQUEUE: reject: RCPT from unknown[50.60.146.24]: 454 4.7.1 returntest@mydnstools.info: Relay access denied; from=relaytest@mydomain.fr to=returntest@mydnstools.info proto=SMTP helo=<relaytest.mydnstools.info>

Thanks

**Comment by cheeseplus** [comment]
Could we get some more information on why this is required a repro case?
