### ISSUE TITLE
No directory /var/run/fail2ban created during installation

### ISSUE THREAD

**Issue by resmonit** [sous-chefs/fail2ban#52]
### Cookbook version
"fail2ban","version":"5.0.1"

### Chef-client version
chef-12.20.3-1.el7.x86_64
chef-server-core-12.15.8-1.el7.x86_64

### Platform Details
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Linux 3.10.0-693.17.1.el7.x86_64 x86_64 GNU/Linux

### Scenario:
Fail2ban cannot start with command: "systemctl start fail2ban.service"

### Steps to Reproduce:
1. Try to start Fail2ban with command: "systemctl start fail2ban.service"
2. Check for directory existence (dir /var/run/fail2ban was not created automatically during the installation)

Error captured in /var/log/messages
chef fail2ban-client: ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
chef systemd: fail2ban.service: control process exited, code=exited status=255
chef systemd: Failed to start Fail2Ban Service.
chef systemd: Unit fail2ban.service entered failed state.
3. Manually create missing dir (mkdir -p /var/run/fail2ban)
4. Fail2ban was properly started with command: systemctl start fail2ban.service

### Expected Result:
There should be possible to start Fail2ban without changing the paths (when Fail2ban cookbook is included with Berksfile).

### Actual Result:
Actually, Fail2ban was included with Berksfile, variables are overwritten with environment variables.
If we change the path to fail2ban.sock file from /var/run/fail2ban/fail2ban.sock into /var/run/fail2ban.sock - other installation parts will still use old path. Temporary fix would be to manually created missing /var/run/fail2ban dir.

**Comment by tristanbrown** [comment]
Even if you manually create this directory after installation, it is wiped out on reboot. The directory needs to be created on every boot.
