### ISSUE TITLE
New Tagged Version

### ISSUE THREAD

**Issue by Rockstar04** [sous-chefs/fail2ban#57]
A patch has already been submitted to correct the cookbook on Ubuntu 18.04, but a new release has not been submitted to the Supermarket. Would it be possible to tag and submit a new release so this cookbook will correctly work with Ubuntu 18.04+?

## Issue Report Details
<dl>
  <dt>Cookbook version</dt>
  <dd>5.0.2</dd>

  <dt>Chef-client version</dt>
  <dd>14.7.17</dd>

  <dt>Platform Details</dt>
  <dd>18.04.1</dd>

  <dt>Scenario</dt>
  <dd>Cookbook fails to correctly detect the system version of fail2ban.</dd>

  <dt>Steps to Reproduce</dt>
  <dd>Run cookbook on Ubuntu 18.04</dd>

  <dt>Expected Result</dt>
  <dd>Correct config syntax is used.</dd>

  <dt>Actual Result</dt>
  <dd>Old (< 0.9) config syntax is used.</dd>
</dl>

**Comment by TravisWhitehead** [comment]
I would also much appreciate a version bump (in order to use the jail resource). :smile:

**Comment by tas50** [comment]
6.1 is up. Closing this out now
