### ISSUE TITLE
Priority field to fail2ban_jail Resource

### ISSUE THREAD

**Issue by djessich** [sous-chefs/fail2ban#61]
### Cookbook version
6.0.0

### Chef-client version
14.12.9

### Platform Details
CentOS 7

### Scenario:
I want to set the priority of the Fail2Ban Jail in conf.d directory.

### Steps to Reproduce:
Call fail2ban_jail resource. This should be an improvement.

### Expected Result:
Expect to create Fail2Ban Jail with priority in conf.d directory for Jail.

### Actual Result:
Priority is hardcoded to 50.

```ruby
# ...
action :create do
  template "/etc/fail2ban/jail.d/50-#{new_resource.jail}.conf" do # priority hardcoded to 50
    # ...
  end
end
# ...
```

Should be something like:
```ruby
# ...
property :priority, [String, Integer], default: '50'
# ...
action :create do
  template "/etc/fail2ban/jail.d/#{new_resource.priority}-#{new_resource.jail}.conf" do # priority hardcoded to 50
    # ...
  end
end
# ...
```

See https://github.com/chef-cookbooks/fail2ban/blob/v6.0.0/resources/jail.rb#L31.

**Comment by djessich** [comment]
Problem still exists, any hints yet?

**Comment by ramereth** [comment]
@djessich please feel free to create a PR which addresses this and we can merge it in!
